version: '2'
services:
  console:
    build:
      context: ./services/console
      dockerfile: Dockerfile
    volumes_from:
      - php
    tty: true
  web:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./app/images/nginx/config:/etc/nginx/conf.d
  php:
    build:
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - ./app/web:/usr/share/nginx/html
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASES: "xdh"
      MYSQL_USER: 'xdh'
      MYSQL_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "root"

volumes:
    db:
      driver: local
